version: '3'
services:

  httpservergp:
    build:
      context: ./docker/php81-apache
    image: php81apache:gp
    container_name: httpservergp
    hostname: httpservergp
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
    tty: true
    working_dir: /var/www
    ports:
      - "80:80"
    depends_on:
      - mysqldb
    volumes:
      - "./../src/:/var/www/"
      - "./etc/php/local.ini:/usr/local/etc/php/conf.d/local.ini"
      - "./etc/apache/000-dev.conf:/etc/apache2/sites-enabled/000-default.conf"
      - "./etc/supervisor/:/etc/supervisor/conf.d/"
    networks:
      public_net:
        ipv4_address: ${HTTPSERVER_IP}

  mysqldb:
    image: mysql:5.7.22
    container_name: mysqldb
    hostname: mysqldb
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: demogp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      TZ: Etc/UTC
    volumes:
      - mysqldb:/var/lib/mysql/
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      public_net:
        ipv4_address: ${MYSQLDB_IP}

  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      public_net:
        ipv4_address: ${ADMINER_IP}

#Docker Networks
networks:
  public_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}

#Volumes
volumes:
  mysqldb:
    driver: local
